### ISSUE TITLE
[BUG] `eww` ends suddenly with 'called `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by smb374** [elkowar/eww#478]
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

`eww` ends suddenly with:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', crates/eww/src/widgets/widget_definitions.rs:160:5
```
appeared in the log of `eww`

### Reproducing the issue

Currently investigating, since this bug will trigger without any prior indication or error.
I can provide my whole config if you need it.

### Expected behaviour

`eww` is expected to run normally, or at least provide more precise information for me to figure out myself.

### Additional context

- `eww` v0.3.0 tag, release build with debug symbols included
- Arch Linux
- `gtk3` 3.24.34
- AMD cpu and gpu, open source drivers

<details>
<summary>Full stack trace with `RUST_BACKTRACE=full`</summary>

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', crates/eww/src/widgets/widget_definitions.rs:160:5
stack backtrace:
   0:     0x55876dc4c05d - std::backtrace_rs::backtrace::libunwind::trace::h30650d5a576fee96
                               at /rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55876dc4c05d - std::backtrace_rs::backtrace::trace_unsynchronized::h120478f92f14ef32
                               at /rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55876dc4c05d - std::sys_common::backtrace::_print_fmt::hfefac89a91107319
                               at /rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55876dc4c05d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h95cae2e6ee00e1c9
                               at /rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55876dc72c9c - core::fmt::write::h43fb3a20100ff4bf
                               at /rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/core/src/fmt/mod.rs:1194:17
   5:     0x55876dc46461 - std::io::Write::write_fmt::h482681b27e1107c6
                               at /rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/std/src/io/mod.rs:1655:15
   6:     0x55876dc4d875 - std::sys_common::backtrace::_print::h5370569609378bde
                               at /rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55876dc4d875 - std::sys_common::backtrace::print::ha3b94bef6c81dfdf
                               at /rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55876dc4d875 - std::panicking::default_hook::{{closure}}::h69cb3d0e19823fae
                               at /rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/std/src/panicking.rs:295:22
   9:     0x55876dc4d4e9 - std::panicking::default_hook::he696194e699ef9fe
                               at /rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/std/src/panicking.rs:314:9
  10:     0x55876dc4de48 - std::panicking::rust_panic_with_hook::h26914bd137f20232
                               at /rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/std/src/panicking.rs:698:17
  11:     0x55876dc4dcb9 - std::panicking::begin_panic_handler::{{closure}}::hcad5d9b3952d4536
                               at /rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/std/src/panicking.rs:586:13
  12:     0x55876dc4c514 - std::sys_common::backtrace::__rust_end_short_backtrace::h90cc3ff955f09e9a
                               at /rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x55876dc4da29 - rust_begin_unwind
                               at /rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/std/src/panicking.rs:584:5
  14:     0x55876d76fa33 - core::panicking::panic_fmt::hf9fef810e6c05b9c
                               at /rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/core/src/panicking.rs:142:14
  15:     0x55876d76f8fd - core::panicking::panic::hb6211ea6f24b0f6c
                               at /rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/core/src/panicking.rs:48:5
  16:     0x55876d7b05b8 - core::option::Option<T>::unwrap::h6b0fe463cb3329e6
                               at /rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/core/src/option.rs:755:21
  17:     0x55876d7b05b8 - eww::widgets::widget_definitions::resolve_widget_attrs::{{closure}}::hed9fb2d137ecdd67
                               at /home/poyehchen/eww/crates/eww/src/widgets/def_widget_macro.rs:48:55
  18:     0x55876d884cc7 - eww::state::scope_graph::ScopeGraph::call_listeners_in_scope::h43dc771f3ccb3166
                               at /home/poyehchen/eww/crates/eww/src/state/scope_graph.rs:292:35
  19:     0x55876d884cc7 - eww::state::scope_graph::ScopeGraph::notify_value_changed::ha711aff219740279
                               at /home/poyehchen/eww/crates/eww/src/state/scope_graph.rs:276:9
  20:     0x55876d884e20 - eww::state::scope_graph::ScopeGraph::notify_value_changed::ha711aff219740279
                               at /home/poyehchen/eww/crates/eww/src/state/scope_graph.rs:281:13
  21:     0x55876d8844b9 - eww::state::scope_graph::ScopeGraph::update_value::h4f403d4a43e71088
                               at /home/poyehchen/eww/crates/eww/src/state/scope_graph.rs:254:9
  22:     0x55876d89306c - eww::state::scope_graph::ScopeGraph::update_global_value::ha61943fd46a504e1
                               at /home/poyehchen/eww/crates/eww/src/state/scope_graph.rs:82:9
  23:     0x55876d89306c - eww::app::App::update_global_state::hbd41f3c603758002
                               at /home/poyehchen/eww/crates/eww/src/app.rs:243:22
  24:     0x55876d89306c - eww::app::App::handle_command::h83b169b44f5b5dc1
                               at /home/poyehchen/eww/crates/eww/src/app.rs:123:25
  25:     0x55876d84d084 - eww::server::initialize_server::{{closure}}::h25cb0693bc813e47
                               at /home/poyehchen/eww/crates/eww/src/server.rs:105:21
  26:     0x55876d84d084 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h71346c46b9d7bc96
                               at /rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/core/src/future/mod.rs:91:19
  27:     0x55876dc2569c - <glib::main_context_futures::FutureWrapper as core::future::future::Future>::poll::hb173dde736e92fdc
  28:     0x55876dc2569c - glib::main_context_futures::TaskSource::poll::{{closure}}::h0a4340c2d98762a2
                               at /home/poyehchen/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.14.8/src/main_context_futures.rs:206:13
  29:     0x55876dc2569c - glib::main_context::<impl glib::auto::main_context::MainContext>::with_thread_default::h5db5c7746fc780ba
                               at /home/poyehchen/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.14.8/src/main_context.rs:125:9
  30:     0x55876dc210aa - glib::main_context_futures::TaskSource::poll::hbadd086bcdb3bf00
                               at /home/poyehchen/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.14.8/src/main_context_futures.rs:200:9
  31:     0x55876dc210aa - glib::main_context_futures::TaskSource::dispatch::hfae8073a9f9384ad
                               at /home/poyehchen/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.14.8/src/main_context_futures.rs:66:34
  32:     0x7f6b335a5c6b - g_main_context_dispatch
  33:     0x7f6b335fc001 - <unknown>
  34:     0x7f6b335a51cf - g_main_loop_run
  35:     0x7f6b32f66e2f - gtk_main
  36:     0x55876d8ac450 - eww::server::initialize_server::h818a53b98ab9f566
                               at /home/poyehchen/eww/crates/eww/src/server.rs:112:5
  37:     0x55876d89a3c9 - eww::main::h7756449a868b292b
                               at /home/poyehchen/eww/crates/eww/src/main.rs:94:35
  38:     0x55876d889273 - core::ops::function::FnOnce::call_once::h2537323fd370eed1
                               at /rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/core/src/ops/function.rs:248:5
  39:     0x55876d889273 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3b14992aca3217bb
                               at /rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/std/src/sys_common/backtrace.rs:122:18
  40:     0x55876d856859 - std::rt::lang_start::{{closure}}::hc76348a64b8a07c2
                               at /rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/std/src/rt.rs:145:18
  41:     0x55876dc3ff6e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hc1b99587df929d1a
                               at /rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/core/src/ops/function.rs:280:13
  42:     0x55876dc3ff6e - std::panicking::try::do_call::hd885b0d9b5384265
                               at /rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/std/src/panicking.rs:492:40
  43:     0x55876dc3ff6e - std::panicking::try::h81f5a6cea8e4e9b0
                               at /rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/std/src/panicking.rs:456:19
  44:     0x55876dc3ff6e - std::panic::catch_unwind::h833673b39f897da7
                               at /rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/std/src/panic.rs:137:14
  45:     0x55876dc3ff6e - std::rt::lang_start_internal::{{closure}}::he07a53d149aeeb07
                               at /rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/std/src/rt.rs:128:48
  46:     0x55876dc3ff6e - std::panicking::try::do_call::hd245290f843cea13
                               at /rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/std/src/panicking.rs:492:40
  47:     0x55876dc3ff6e - std::panicking::try::h4eb21d17fa19203f
                               at /rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/std/src/panicking.rs:456:19
  48:     0x55876dc3ff6e - std::panic::catch_unwind::haedb23d6d3939463
                               at /rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/std/src/panic.rs:137:14
  49:     0x55876dc3ff6e - std::rt::lang_start_internal::h95a88e506bad36b1
                               at /rustc/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/library/std/src/rt.rs:128:20
  50:     0x55876d89d618 - main
  51:     0x7f6b328d9290 - <unknown>
  52:     0x7f6b328d934a - __libc_start_main
  53:     0x55876d76fd25 - _start
                               at /build/glibc/src/glibc/csu/../sysdeps/x86_64/start.S:115
  54:                0x0 - <unknown>
```

</details>

<details>
<summary>Quick reference of the code that the error occurred</summary>

```rust
// path: crates/eww/src/widgets/widget_definitions.rs
// ...
pub(super) fn resolve_widget_attrs(bargs: &mut BuilderArgs, gtk_widget: &gtk::Widget) -> Result<()> {
    let deprecated: HashSet<_> = DEPRECATED_ATTRS.to_owned();
    let contained_deprecated: Vec<_> = bargs.unhandled_attrs.drain_filter(|a| deprecated.contains(&a.0 as &str)).collect();
    if !contained_deprecated.is_empty() {
        let diag = error_handling_ctx::stringify_diagnostic(gen_diagnostic! {
            kind =  Severity::Error,
            msg = "Unsupported attributes provided",
            label = bargs.widget_use.span => "Found in here",
            note = format!("The attribute(s) ({}) has/have been removed, as GTK does not support it consistently. Instead, use eventbox to wrap this widget and set the attribute there. See #251 (https://github.com/elkowar/eww/issues/251) for more details.", contained_deprecated.iter().join(", ")),
        }).unwrap();
        eprintln!("{}", diag);
    }

    let css_provider = gtk::CssProvider::new();

    let visible_result: Result<_> = try {
        let visible_expr = bargs.widget_use.attrs.attrs.get("visible").map(|x| x.value.as_simplexpr()).transpose()?;
        if let Some(visible_expr) = visible_expr {
            let visible = bargs.scope_graph.evaluate_simplexpr_in_scope(bargs.calling_scope, &visible_expr)?.as_bool()?;
            connect_first_map(gtk_widget, move |w| {
                if visible {
                    w.show();
                } else {
                    w.hide();
                }
            });
        }
    };
    if let Err(err) = visible_result {
        error_handling_ctx::print_error(err);
    }

    def_widget!(bargs, _g, gtk_widget, { // <- `Option::unwrap()` called here.
        // @prop class - css class name
        prop(class: as_string) {
            // TODO currently this overrides classes that gtk adds automatically, which is kinda stupid...
            let old_classes = gtk_widget.style_context().list_classes();
            let old_classes = old_classes.iter().map(|x| x.as_str()).collect::<Vec<&str>>();
            let new_classes = class.split(' ').collect::<Vec<_>>();
            let (missing, new) = list_difference(&old_classes, &new_classes);
            for class in missing {
                gtk_widget.style_context().remove_class(class);
            }
            for class in new {
                gtk_widget.style_context().add_class(class);
            }
        },
        // @prop valign - how to align this vertically. possible values: $alignment
        prop(valign: as_string) { gtk_widget.set_valign(parse_align(&valign)?) },
        // @prop halign - how to align this horizontally. possible values: $alignment
        prop(halign: as_string) { gtk_widget.set_halign(parse_align(&halign)?) },
        // @prop vexpand - should this container expand vertically. Default: false.
        prop(vexpand: as_bool = false) { gtk_widget.set_vexpand(vexpand) },
        // @prop hexpand - should this widget expand horizontally. Default: false.
        prop(hexpand: as_bool = false) { gtk_widget.set_hexpand(hexpand) },
        // @prop width - width of this element. note that this can not restrict the size if the contents stretch it
        // @prop height - height of this element. note that this can not restrict the size if the contents stretch it
        prop(width: as_i32?, height: as_i32?) {
            gtk_widget.set_size_request(
                width.unwrap_or_else(|| gtk_widget.allocated_width()),
                height.unwrap_or_else(|| gtk_widget.allocated_height())
            );
        },
        // @prop active - If this widget can be interacted with
        prop(active: as_bool = true) { gtk_widget.set_sensitive(active) },
        // @prop tooltip - tooltip text (on hover)
        prop(tooltip: as_string) {
            gtk_widget.set_tooltip_text(Some(&tooltip));
        },
        // @prop visible - visibility of the widget
        prop(visible: as_bool = true) {
            if visible { gtk_widget.show(); } else { gtk_widget.hide(); }
        },
        // @prop style - inline css style applied to the widget
        prop(style: as_string) {
            gtk_widget.reset_style();
            css_provider.load_from_data(format!("* {{ {} }}", style).as_bytes())?;
            gtk_widget.style_context().add_provider(&css_provider, gtk::STYLE_PROVIDER_PRIORITY_APPLICATION)
        },
    });
    Ok(())
}
// ...
```

</details>

**Comment by viandoxdev** [comment]
Could you try this patch ? I've been having a similar problem and '''''fixed''''' it that way.
```patch
diff --git a/crates/eww/src/widgets/def_widget_macro.rs b/crates/eww/src/widgets/def_widget_macro.rs
index 14beee3..907012f 100644
--- a/crates/eww/src/widgets/def_widget_macro.rs
+++ b/crates/eww/src/widgets/def_widget_macro.rs
@@ -42,7 +42,8 @@ macro_rules! def_widget {
                             f: Box::new({
                                 let $gtk_widget = gdk::glib::clone::Downgrade::downgrade(&$gtk_widget);
                                 move |$scope_graph, values| {
-                                    let $gtk_widget = gdk::glib::clone::Upgrade::upgrade(&$gtk_widget).unwrap();
+                                    let $gtk_widget = gdk::glib::clone::Upgrade::upgrade(&$gtk_widget)
+                                        .ok_or_else(|| anyhow!("Couldn't upgrade reference."))?;
                                     // values is a map of all the variables that are required to evaluate the
                                     // attributes expression.
 

```

**Comment by smb374** [comment]
@viandoxdev tried the patch, currently no problems.
It seems like that the `$gtk_widget` is somehow dropped after downgrading it to obtain a weak reference before the weak reference is used in the closure right after.
Pretty strange to me.

**Comment by viandoxdev** [comment]
If you get a log anytime saying something like: "error: ... Caused by: couldn't upgrade reference" then this is definitely that. No clue why it happens tho. The fact that just ignoring the error works is really weird, either this isn't actually a fix and is causing other problems that I haven't noticed, or the objects are dead by this point and eww just shouldn't have a reference to them. I only started getting the error when my config started getting really complex (hundreds of widgets, 20+ updating variables), but the error is pretty common for me now.

**Comment by smb374** [comment]
Yes, I use `for` widget for workspace widget, but the array is polled with a predefined initial value and the window contained it are not supposed to be removed as long as the user is still in the window manager.

**Comment by xDarksome** [comment]
Encountered the same problem after my `deflisten` script started to utilize `eww update` pretty frequently.

The proposed patch works fine for now.

**Comment by elkowar** [comment]
Ye, the issue here is that widgets, when removed, will get deallocated -- apparently some bug in the state management system fails to catch that, and thus fails to remove the respective state update callback, which caused this panic. ignoring it works as the widget doesn't actually exist anymore, so nothing is lost. I'll need to investigate that bug in the state management
